// <auto-generated />
using System;
using InternshipPortal.API.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipPortal.API.Data.Migrations
{
    [DbContext(typeof(InternshipPortalContext))]
    [Migration("20260106185552_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("InternshipId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC07AC8AEACA");

                    b.HasIndex(new[] { "InternshipId" }, "IX_Applications_InternshipId");

                    b.HasIndex(new[] { "UserId" }, "IX_Applications_UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07554CAA72");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id")
                        .HasName("PK__Companie__3214EC07C18E3342");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deadline")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("Remote")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id")
                        .HasName("PK__Internsh__3214EC07C5C66436");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Internships_CategoryId");

                    b.HasIndex(new[] { "CompanyId" }, "IX_Internships_CompanyId");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0779B422BC");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4E7CA1934")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Application", b =>
                {
                    b.HasOne("InternshipPortal.API.Data.EF.Internship", "Internship")
                        .WithMany("Applications")
                        .HasForeignKey("InternshipId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Internships");

                    b.HasOne("InternshipPortal.API.Data.EF.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Users");

                    b.Navigation("Internship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Internship", b =>
                {
                    b.HasOne("InternshipPortal.API.Data.EF.Category", "Category")
                        .WithMany("Internships")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Internships_Categories");

                    b.HasOne("InternshipPortal.API.Data.EF.Company", "Company")
                        .WithMany("Internships")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Internships_Companies");

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Category", b =>
                {
                    b.Navigation("Internships");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Company", b =>
                {
                    b.Navigation("Internships");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.Internship", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("InternshipPortal.API.Data.EF.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
